# Generated by Django 5.1.6 on 2025-02-05 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
                ('Cantidad', models.PositiveIntegerField()),
                ('Marca', models.CharField(max_length=100)),
                ('Fecha_empaquetado', models.DateTimeField(auto_now=True)),
                ('Fecha_vencimiento', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
