# Generated by Django 5.1.6 on 2025-02-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productos_fecha_empaquetado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Fecha_vencimiento',
        ),
        migrations.AlterField(
            model_name='productos',
            name='Fecha_empaquetado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
